import HashRouter, {
  Route,
  HASH_ROUTING_INIT_ROUTING,
  HASH_ROUTING_SET_NEXT_ROUTE,
  HASH_ROUTING_SWITCH_ROUTE,
  HASH_ROUTING_UPDATE_ACCESS_TO_ROUTE
} from './hash-router'

export default HashRouter
export {
  Route,
  HASH_ROUTING_INIT_ROUTING,
  HASH_ROUTING_SET_NEXT_ROUTE,
  HASH_ROUTING_SWITCH_ROUTE,
  HASH_ROUTING_UPDATE_ACCESS_TO_ROUTE
}
